### ISSUE TITLE
RGT cycling won’t connect

### ISSUE THREAD

**Issue by lloydar10** [djwasser/M3iPiZeroW#4]
M3iPi appears as ftms - but it won’t connect.
![6F396ED3-E809-4F4F-9B51-9BD6C3E641D7](https://user-images.githubusercontent.com/87810836/127164962-342829f8-b983-41b5-abfe-07cbccf70341.jpeg)

the other converter in image (Keiser m series appears as power meter - which works/connects)

**Comment by djwasser** [comment]
Reviewing notes: Cycling Power Service is not "known to work" so possibly is not implemented correctly...  

Further investigation is required, so leaving this issue open.

**Comment by nealjane** [comment]
I have no idea if this is anything - just checking ‘Keiser m series converter’ with nRF connect shows the following for 2a65 (0x00)  attached pic
whereas m3iPiZeroW and keiser2zwift both have 2a65 shown as 0x08 in ble folder - I’m not sure whether keiser2zwift power profile worked (didn’t work with RGT either) ??

![11A5F7A5-227F-462A-8C5D-0B4C3F614FC0](https://user-images.githubusercontent.com/68538658/127490674-f6fe77be-20ae-4457-8dca-cb1445190c57.jpeg)

**Comment by djwasser** [comment]
@nealjane @Lloydster2000 
Thanks for feedback and analysis.  I played around a bit and found that, if I disabled the Fitness Machine Service (FTMS), RGT Cycling found Power and Cadence (but not HR).  I then tested Zwift, FulGaz, and Kinomap they all are stilll able to see Power, Cadence and HR.  Peloton also still sees Cadence and HR.  So I am just leaving FTMS disabled for now.

Based on the behavior I see with RGT, it seems that RGT only finds one service associtaed with a bluetooth source.  So it latches on to the one it finds first and does not look for others.  Any way, RGT finds power (and cadence) now that I have stopped advertising FTMS.  Not sure if there is a way to get it to see HR from M3I...

**Comment by lloydar10** [comment]
RGT doesn’t populate hr from a polar h10 (connected to bike) even with real Keiser converter, you have to go to hr and select the polar Bluetooth separately- so your converters no different there.

just updated m3iPiZeroW- it wouldn’t connect to RGT, but interestingly zwift found power, cadence and hr through your converter.
![80F2E9B1-B278-4B04-8FE8-77A46D87B891](https://user-images.githubusercontent.com/87810836/127541129-a4e3e9b4-0330-4f89-943c-81f705c8e0fe.png)

I’m just doing a clean install - to see if I can get RGT working..👍🏻

Ps- update worked- RGT power and cadence, 
zwift - power cadence and hr from polar h10 through bike Bluetooth working also👏

**Comment by djwasser** [comment]
@Lloydster2000 - Thanks for verifying that this works for you. I will go ahead and close the issue.
